image: Visual Studio 2019

environment:
    matrix:
      - solution_name: ParallelAndSynchronousMatrixMultiplication/ParallelAndSynchronousMatrixMultiplication.sln
      - solution_name: Lazy/Lazy.sln
      - solution_name: SimpleFTP/SimpleFTP.sln
      - solution_name: GuiForSimpleFTP/GuiForSimpleFTP.sln
    
before_build:
  - nuget restore %solution_name%

build_script:
  - dotnet build %solution_name%

test_script:
  - dotnet test %solution_name%